"""统一管理项目内所有自定义 LLM Prompt。"""

from prompts.review import (
    REVIEW_CARD_PROMPT_VERSION,
    REVIEW_CARD_REWRITE_PROMPT_VERSION,
    REVIEW_MATERIAL_REWRITE_PROMPT_VERSION,
)

__all__ = [
    "REVIEW_CARD_PROMPT_VERSION",
    "REVIEW_CARD_REWRITE_PROMPT_VERSION",
    "REVIEW_MATERIAL_REWRITE_PROMPT_VERSION",
]
