CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account VARCHAR(120) NOT NULL UNIQUE,
    email VARCHAR(160),
    display_name VARCHAR(80) NOT NULL,
    role VARCHAR(40) NOT NULL DEFAULT 'ADMIN',
    password_hash VARCHAR(128) NOT NULL,
    password_salt VARCHAR(128) NOT NULL,
    password_algorithm VARCHAR(40) NOT NULL DEFAULT 'PBKDF2WithHmacSHA256',
    password_iterations INTEGER NOT NULL DEFAULT 120000,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    remember_me BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auth_session_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS auth_login_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    account VARCHAR(120) NOT NULL,
    success BOOLEAN NOT NULL,
    failure_reason VARCHAR(255),
    ip_address VARCHAR(80),
    user_agent VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auth_login_record_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS learning_material (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    user_id VARCHAR(120) NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    source VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    parser VARCHAR(80),
    document_summary CLOB,
    chunk_count INTEGER DEFAULT 0,
    original_filename VARCHAR(255),
    original_file_path VARCHAR(500),
    storage_type VARCHAR(30) NOT NULL DEFAULT 'local',
    object_key VARCHAR(700),
    public_url VARCHAR(700),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rag_query_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(120) NOT NULL,
    task_id VARCHAR(120),
    question CLOB NOT NULL,
    answer CLOB,
    status VARCHAR(30) NOT NULL,
    top_k INTEGER NOT NULL DEFAULT 5,
    evidence_count INTEGER NOT NULL DEFAULT 0,
    expanded_queries_json CLOB NOT NULL DEFAULT '[]',
    evidences_json CLOB NOT NULL DEFAULT '[]',
    diagnostics_json CLOB NOT NULL DEFAULT '{}',
    progress_events_json CLOB NOT NULL DEFAULT '[]',
    error_message VARCHAR(1000),
    duration_ms INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS log_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(80) NOT NULL,
    session_id VARCHAR(120),
    user_id VARCHAR(120) NOT NULL DEFAULT 'anonymous',
    source VARCHAR(30) NOT NULL,
    domain VARCHAR(50) NOT NULL DEFAULT 'system',
    level VARCHAR(20) NOT NULL DEFAULT 'INFO',
    module VARCHAR(80) NOT NULL,
    stage VARCHAR(80),
    event_type VARCHAR(80) NOT NULL,
    action VARCHAR(120) NOT NULL,
    message VARCHAR(500),
    route VARCHAR(255),
    http_method VARCHAR(20),
    request_path VARCHAR(500),
    status_code INTEGER,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    duration_ms INTEGER,
    material_id BIGINT,
    document_id VARCHAR(120),
    parser VARCHAR(80),
    client_time TIMESTAMP,
    server_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    context_json VARCHAR(20000) DEFAULT '{}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS log_error (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(80) NOT NULL,
    session_id VARCHAR(120),
    user_id VARCHAR(120) NOT NULL DEFAULT 'anonymous',
    source VARCHAR(30) NOT NULL,
    domain VARCHAR(50) NOT NULL DEFAULT 'system',
    severity VARCHAR(20) NOT NULL DEFAULT 'ERROR',
    module VARCHAR(80) NOT NULL,
    stage VARCHAR(80),
    action VARCHAR(120),
    error_type VARCHAR(120) NOT NULL,
    error_code VARCHAR(120),
    message VARCHAR(1000) NOT NULL,
    stack_trace CLOB,
    fingerprint VARCHAR(128) NOT NULL UNIQUE,
    route VARCHAR(255),
    http_method VARCHAR(20),
    request_path VARCHAR(500),
    status_code INTEGER,
    duration_ms INTEGER,
    material_id BIGINT,
    document_id VARCHAR(120),
    parser VARCHAR(80),
    client_time TIMESTAMP,
    server_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    context_json VARCHAR(20000) DEFAULT '{}',
    first_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    occurrence_count INTEGER DEFAULT 1,
    status VARCHAR(30) DEFAULT 'OPEN',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent_conversation_folder (
    id VARCHAR(120) PRIMARY KEY,
    user_id VARCHAR(120) NOT NULL,
    name VARCHAR(80) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_agent_conversation_folder_user_sort
    ON agent_conversation_folder(user_id, sort_order, updated_at DESC);

CREATE TABLE IF NOT EXISTS agent_task (
    id VARCHAR(120) PRIMARY KEY,
    user_id VARCHAR(120) NOT NULL,
    folder_id VARCHAR(120),
    task_type VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'CREATED',
    title VARCHAR(255),
    input_json CLOB NOT NULL DEFAULT '{}',
    plan_json CLOB NOT NULL DEFAULT '{}',
    draft_json CLOB NOT NULL DEFAULT '{}',
    final_json CLOB NOT NULL DEFAULT '{}',
    python_thread_id VARCHAR(160),
    error_code VARCHAR(120),
    error_message VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_task_folder FOREIGN KEY (folder_id) REFERENCES agent_conversation_folder(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_agent_task_user_status_updated
    ON agent_task(user_id, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_task_user_folder_updated
    ON agent_task(user_id, folder_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_task_python_thread
    ON agent_task(python_thread_id);

CREATE TABLE IF NOT EXISTS agent_chat_message (
    id VARCHAR(120) PRIMARY KEY,
    task_id VARCHAR(120) NOT NULL,
    user_id VARCHAR(120) NOT NULL,
    sequence_no BIGINT NOT NULL DEFAULT 0,
    role VARCHAR(30) NOT NULL,
    message_type VARCHAR(60) NOT NULL,
    content CLOB NOT NULL,
    payload_json CLOB NOT NULL DEFAULT '{}',
    source_event_type VARCHAR(80),
    source_id VARCHAR(160),
    dedupe_key VARCHAR(220) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_chat_message_task FOREIGN KEY (task_id) REFERENCES agent_task(id) ON DELETE CASCADE,
    CONSTRAINT uk_agent_chat_message_dedupe UNIQUE (task_id, dedupe_key)
);

CREATE INDEX IF NOT EXISTS idx_agent_chat_message_task_created
    ON agent_chat_message(task_id, created_at);

CREATE UNIQUE INDEX IF NOT EXISTS uk_agent_chat_message_task_sequence
    ON agent_chat_message(task_id, sequence_no);

CREATE INDEX IF NOT EXISTS idx_agent_chat_message_user_updated
    ON agent_chat_message(user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS agent_conversation_summary (
    id VARCHAR(120) PRIMARY KEY,
    task_id VARCHAR(120) NOT NULL,
    user_id VARCHAR(120) NOT NULL,
    summary_type VARCHAR(40) NOT NULL DEFAULT 'CONTEXT_COMPRESSION',
    covered_message_start_id VARCHAR(120),
    covered_message_end_id VARCHAR(120),
    covered_message_count INTEGER NOT NULL DEFAULT 0,
    raw_token_estimate INTEGER NOT NULL DEFAULT 0,
    compressed_token_estimate INTEGER NOT NULL DEFAULT 0,
    summary_json CLOB NOT NULL DEFAULT '{}',
    summary_text CLOB NOT NULL,
    key_facts_json CLOB NOT NULL DEFAULT '[]',
    evidence_refs_json CLOB NOT NULL DEFAULT '[]',
    compression_model VARCHAR(120),
    compression_prompt_version VARCHAR(80) NOT NULL DEFAULT 'agent-context-compression-v1',
    compression_version INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    diagnostics_json CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_conversation_summary_task FOREIGN KEY (task_id) REFERENCES agent_task(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_agent_conversation_summary_task_status_updated
    ON agent_conversation_summary(task_id, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_conversation_summary_user_task_status
    ON agent_conversation_summary(user_id, task_id, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_conversation_summary_covered_range
    ON agent_conversation_summary(task_id, covered_message_start_id, covered_message_end_id);

CREATE TABLE IF NOT EXISTS agent_tool_call (
    id VARCHAR(120) PRIMARY KEY,
    task_id VARCHAR(120) NOT NULL,
    tool_name VARCHAR(120) NOT NULL,
    tool_type VARCHAR(30) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    request_json CLOB NOT NULL DEFAULT '{}',
    response_json CLOB NOT NULL DEFAULT '{}',
    ownership_verified BOOLEAN NOT NULL DEFAULT FALSE,
    scope VARCHAR(80) NOT NULL DEFAULT 'current_user_or_authorized',
    error_code VARCHAR(120),
    error_message VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_tool_call_task FOREIGN KEY (task_id) REFERENCES agent_task(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_agent_tool_call_task_created
    ON agent_tool_call(task_id, created_at);

CREATE INDEX IF NOT EXISTS idx_agent_tool_call_status
    ON agent_tool_call(status);

CREATE TABLE IF NOT EXISTS agent_human_review (
    id VARCHAR(120) PRIMARY KEY,
    task_id VARCHAR(120) NOT NULL,
    review_type VARCHAR(30) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    proposal_json CLOB NOT NULL DEFAULT '{}',
    decision_json CLOB NOT NULL DEFAULT '{}',
    reviewed_by VARCHAR(120),
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    CONSTRAINT fk_agent_human_review_task FOREIGN KEY (task_id) REFERENCES agent_task(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_agent_human_review_task_status
    ON agent_human_review(task_id, status);

CREATE INDEX IF NOT EXISTS idx_agent_human_review_expires
    ON agent_human_review(expires_at);

CREATE TABLE IF NOT EXISTS agent_operation (
    id VARCHAR(120) PRIMARY KEY,
    task_id VARCHAR(120) NOT NULL,
    review_id VARCHAR(120),
    user_id VARCHAR(120) NOT NULL,
    operation_type VARCHAR(80) NOT NULL,
    resource_type VARCHAR(80) NOT NULL,
    resource_id VARCHAR(120) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING_APPROVAL',
    before_snapshot_ref VARCHAR(180),
    after_snapshot_ref VARCHAR(180),
    idempotency_key VARCHAR(160) NOT NULL,
    undo_deadline TIMESTAMP,
    audit_event_id BIGINT,
    error_code VARCHAR(120),
    error_message VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_operation_task FOREIGN KEY (task_id) REFERENCES agent_task(id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_operation_review FOREIGN KEY (review_id) REFERENCES agent_human_review(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_agent_operation_idempotency
    ON agent_operation(user_id, operation_type, resource_type, resource_id, idempotency_key);

CREATE INDEX IF NOT EXISTS idx_agent_operation_task_status
    ON agent_operation(task_id, status);

CREATE INDEX IF NOT EXISTS idx_agent_operation_user_status
    ON agent_operation(user_id, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_operation_resource
    ON agent_operation(resource_type, resource_id);

CREATE TABLE IF NOT EXISTS agent_operation_snapshot (
    id VARCHAR(120) PRIMARY KEY,
    operation_id VARCHAR(120) NOT NULL,
    snapshot_type VARCHAR(20) NOT NULL,
    resource_type VARCHAR(80) NOT NULL,
    resource_id VARCHAR(120) NOT NULL,
    snapshot_json CLOB NOT NULL DEFAULT '{}',
    content_hash VARCHAR(128) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_operation_snapshot_operation FOREIGN KEY (operation_id) REFERENCES agent_operation(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_agent_operation_snapshot_operation
    ON agent_operation_snapshot(operation_id, snapshot_type);

CREATE TABLE IF NOT EXISTS agent_memory_item (
    id VARCHAR(120) PRIMARY KEY,
    user_id VARCHAR(120) NOT NULL,
    memory_type VARCHAR(40) NOT NULL,
    namespace VARCHAR(80) NOT NULL,
    scope_type VARCHAR(30) NOT NULL,
    scope_id VARCHAR(120),
    subject_key VARCHAR(120) NOT NULL,
    content CLOB NOT NULL,
    summary CLOB NOT NULL,
    evidence_refs_json CLOB NOT NULL DEFAULT '[]',
    source_task_id VARCHAR(120),
    source_tool_call_id VARCHAR(120),
    source_review_id VARCHAR(120),
    source_hash VARCHAR(128) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING_REVIEW',
    confidence DECIMAL(5, 4) NOT NULL DEFAULT 0.5000,
    importance DECIMAL(5, 4) NOT NULL DEFAULT 0.5000,
    sensitivity_level VARCHAR(20) NOT NULL DEFAULT 'LOW',
    consent_source VARCHAR(40) NOT NULL DEFAULT 'AGENT_INFERRED',
    access_count INTEGER NOT NULL DEFAULT 0,
    last_accessed_at TIMESTAMP,
    valid_from TIMESTAMP,
    valid_until TIMESTAMP,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_memory_item_task FOREIGN KEY (source_task_id) REFERENCES agent_task(id) ON DELETE SET NULL,
    CONSTRAINT fk_agent_memory_item_tool_call FOREIGN KEY (source_tool_call_id) REFERENCES agent_tool_call(id) ON DELETE SET NULL,
    CONSTRAINT fk_agent_memory_item_review FOREIGN KEY (source_review_id) REFERENCES agent_human_review(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_agent_memory_item_user_status_updated
    ON agent_memory_item(user_id, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_memory_item_lookup
    ON agent_memory_item(user_id, namespace, subject_key, scope_type, status);

CREATE INDEX IF NOT EXISTS idx_agent_memory_item_source_task
    ON agent_memory_item(source_task_id);

CREATE TABLE IF NOT EXISTS agent_memory_embedding (
    id VARCHAR(120) PRIMARY KEY,
    memory_id VARCHAR(120) NOT NULL,
    user_id VARCHAR(120) NOT NULL,
    chunk_id VARCHAR(180) NOT NULL,
    retrieval_text CLOB NOT NULL,
    term_counts CLOB NOT NULL DEFAULT '{}',
    embedding CLOB NOT NULL DEFAULT '[]',
    metadata CLOB NOT NULL DEFAULT '{}',
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_memory_embedding_memory FOREIGN KEY (memory_id) REFERENCES agent_memory_item(id) ON DELETE CASCADE,
    CONSTRAINT uk_agent_memory_embedding_chunk UNIQUE (memory_id, chunk_id)
);

CREATE INDEX IF NOT EXISTS idx_agent_memory_embedding_memory
    ON agent_memory_embedding(memory_id);

CREATE INDEX IF NOT EXISTS idx_agent_memory_embedding_user_status
    ON agent_memory_embedding(user_id, status, deleted_at);

CREATE TABLE IF NOT EXISTS agent_memory_version (
    id VARCHAR(120) PRIMARY KEY,
    memory_id VARCHAR(120) NOT NULL,
    previous_memory_id VARCHAR(120),
    relation_type VARCHAR(40) NOT NULL,
    decision VARCHAR(40) NOT NULL,
    reason VARCHAR(1000),
    decided_by VARCHAR(60) NOT NULL,
    user_id VARCHAR(120) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_memory_version_memory FOREIGN KEY (memory_id) REFERENCES agent_memory_item(id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_memory_version_previous FOREIGN KEY (previous_memory_id) REFERENCES agent_memory_item(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_agent_memory_version_memory
    ON agent_memory_version(memory_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_memory_version_previous
    ON agent_memory_version(previous_memory_id);

CREATE TABLE IF NOT EXISTS agent_memory_audit (
    id VARCHAR(120) PRIMARY KEY,
    memory_id VARCHAR(120),
    user_id VARCHAR(120) NOT NULL,
    task_id VARCHAR(120),
    action VARCHAR(60) NOT NULL,
    actor_type VARCHAR(60) NOT NULL,
    before_hash VARCHAR(128),
    after_hash VARCHAR(128),
    summary VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_memory_audit_memory FOREIGN KEY (memory_id) REFERENCES agent_memory_item(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_agent_memory_audit_memory_created
    ON agent_memory_audit(memory_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_memory_audit_user_created
    ON agent_memory_audit(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS system_setting (
    setting_key VARCHAR(120) PRIMARY KEY,
    setting_group VARCHAR(80) NOT NULL,
    label VARCHAR(120) NOT NULL,
    setting_value VARCHAR(500) NOT NULL,
    sort_order INTEGER DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
